name: ${REPO_NAME_LOWER}
services:
    server:
        image: ${DOCKER_REGISTRY}/${SERVER_DOCKER_IMAGE}:${DOCKER_TAG}
        ports:
            - '3000:3000'
        restart: always
        container_name: server
